### ISSUE TITLE
Column-based attribute storage

### ISSUE THREAD

**Issue by jaakla** [mapbox/vector-tile-spec#105] opened 2018-03-22 14:50 UTC
One MVT issues is that all the attribute data sits mixed with geometry data, which limits compression and selective data loading possibilities. What about storing data in columnar way:

## how it works
* Keep geometry data in own pbf, as in old format. Only attribute is object local/global id. Maybe even this is not needed, if objects are indexed by order number
* For every attribute there is separate "attribute" file, say 1/2/3.name.pbf. Here for every value there is one row

## interesting properties/advantages of this

* Single column attribute files can be compressed very effectively, e.g. field with no values has close to 0 bytes, can use for example Dremel encoding, dictionary encoding and other dataset / datatype-optimized compression methods. I know mvt already has dictionary encoding internally. In the worst case it would take same amount like old vector tiles with mixed data
* Client loads geometry tile + only these attributes what it really needs
* Can have rendering while still loading data - load 4x smaller vector tile with points/lines etc, render this immediately with generic style, then load attributes and update rendering based on real attribute values.
* Client can cache attribute values, if geometry tiles have global id and defer (lazy) loading of attributes if needed. For example if user zooms out, then some attribute values are already known based on object global IDs (previously loaded attribute), similar thing for big roads/polyons across many tiles in same zoom. 
* Nowadays HTTP request in HTTP/2 is cheap, so client can afford more queries for same tile. Here we reduce bandwidth, but increase number of requests.
* Big data databases are often also columnar, so this kind of query should be faster there
* Perfect for cases where attributes are dynamic (queried/refreshed often), but geometries quite static (cached for long time, pregenerated). For example traffic map use case.
* Attribute can be streamed - client can subscribe to server to get updates for particular tile/column, and server sends only data updates - e.g. {timestamp, object id, new value} triplets, and local column storage is updated. No need to resend whole tiles, geometries etc.
* When data is loaded from server, then can specify server-side functions, e.g. aggregate function (min,max,avg etc) for sampled (low-zoom) data, and filters, without need to reload geometries
* Probably more suitable for single-layer "data-centric" tiles, less wins for generic basemap tiles with a lot of very different layers in single tile.

This is somewhat inspired from Apache Parquet, and adjusted to vector tiles logic.

**Comment by andrewharvey** [comment] 2018-04-14 08:32
Please excuse my limited knowledge of the extent of the MVT spec, if this is something which should happen on top of/external to the spec. But the part I really love about this proposal is to split geometry and attributes into two different mapbox vector tilesets.

If the spec was able to standardise this so so that clients knew how to combine them via a unique key that would unlock these two big uses cases:

1. Geometries that update infrequently with attributes that update frequently. eg. The Mapbox Traffic Tileset. The road geometries update infrequently and only need to be downloaded and cached over a longer time period, but the attributes containing the congestion levels update frequently and can only those attributes need to be downloaded every X seconds.

2. Visualisation of census/statistical data. You might have geometries for census blocks that are fixed, but thousands of possible attributes. With separate geometry and attribute tilesets you could download the geometry once, then as a user chooses a new attribute to visualise the attribute only mvts need to be downloaded.

These are mentioned by @jaakla but I wouldn't go so far as implementing everything. I think it still makes sense for the geometryless mvt's to be tiles. Nor should they only reply attributes the user requests. Nor should there be any server side logic. That said, I feel all those features are out of the mvt scope as a data format, so could easily be left to the implementer.

**Comment by jaakla** [comment] 2018-04-15 07:36
Yes, my original idea was also to implement it on to of existing MVT, so same tooling can be kept. Then this is more a 'tile API'/storage level extension, and you can use old tooling. 

Now when considering new MVT 3 which will be (maybe) not backward-compatible with earlier MVT, then one may consider re-defining MVT 3 as multi-file tiles, leaving "row-based" attributes always in separate files from geometries. In a way Shapefiles and Mapinfo formats have worked that way for decades, or utfgrid more recently, just they use classic row-based format for attributes. Columnal storage would mean new encoding for data file(s). In this case users would never try to mix attributes with geometries, and the column-based storage would become mandatory part of MVT itself.

**Comment by flippmoke** [comment] 2018-07-16 16:20
While I don't want to squash ideas -- the biggest concern overall that I see with this proposal is that it intentionally separates the properties/attributes from the geometry of a feature. This by design is placed together in a VT in order make each tile a complete set of data in a single request from a tile. There is no intention to separate these anytime soon as I think it violates the core design of VTs as a whole and would greatly introduce more complex serving of tiled data. For this reason I am going to go ahead and close this issue, if you would like to discuss this further please feel free to continue to comment in this issue.

**Closed by flippmoke** 2018-07-16 16:20 UTC
Labels: 3.0 Specification

**Comment by jaakla** [comment] 2018-07-17 06:46
Yes, the proposal is for a bit specific cases of data - when data is dynamic (e.g. traffic, weather) or big (time series, iOT etc) or with complex structure (e.g. very big objects, where current approach duplicates a lot of data), then de-duplication of data and geometries makes sense. MVT current version approach in the other hand is more optimal for basemaps and 'simple GIS style', usually static datasets, such as the ones served from Mapbox Studio.
