### ISSUE TITLE
Fixed projection

### ISSUE THREAD

**Issue by sanderd17** [mapbox/vector-tile-spec#31] opened 2015-03-19 08:02 UTC
I don't like the fact that the projection is fixed to spherical Mercator. Because it might limit usage of the format by several official agencies due to the inaccuracies. 

Maybe it would be better to follow a WMS or WMTS system. Where the possible projections are defined on a server manifest, and are accessed by different URIs. Then the definition of the projection can be taken out of the tile spec.

**Comment by tmcw** [comment] 2015-06-23 23:43
Duplicate of #9

**Closed by tmcw** 2015-06-23 23:43 UTC
